remember_me: "1"
max_name: 30
max_email: 60
min_password: 6
time_exprired: 2
custome_valid: 7
host_mail: "smtp.gmail.com"
port_mail: 587
domain_mail: "herokuapp.com"
authentication_mail: "plain"
page_subject: 5
max_subject_name: 120
user_deleted: 1
per_page_exam: 10
default_time: "00:00:00"
hour_num: 60
submit_finish: "Finish"
time_remaning_default: 0
time_spent_format: "%H:%M:%S"
per_page_question: 10
time_zone: "Asia/Bangkok"
per_page_question: 10
question_deleted: 1
